"https://{default}/":
  type: upstream
  upstream: "app:http"
  cache:
    enabled: false
"https://www.{default}/":
  type: redirect
  to: "https://{default}/"

"https://storybook.{default}/":
  type: upstream
  upstream: "storybook:http"
